"""Tunable thresholds. Mechanisms import these; do not restate them."""

DIAGNOSIS_CONFIDENCE_THRESHOLD = 0.5
REGRESSION_GATE_THRESHOLD = 0.8
EVAL_MAX_CASES = 4
REDTEAM_MAX_ATTACKS = 6
SEEN_RING_MAX = 500
WILSON_Z = 1.96
AB_MIN_RUNS = 5
AB_SIGNIFICANT_P = 0.05
AB_MIN_DELTA_PP = 3.0
